# Generated by Django 2.2.2 on 2021-04-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=10, verbose_name='收货人')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
            ],
            options={
                'verbose_name': '收获地址',
                'verbose_name_plural': '收获地址',
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address_id',
            field=models.IntegerField(null=True, verbose_name='默认地址id'),
        ),
    ]
